### PR TITLE
Mark __ functions and methods automatically as internal

### LINKED ISSUE #3: Mark __ functions automatically as internal
We already have support for `@internal` annotations. Functions starting with two underscores (`__`) should automatically be marked as internal and thus no longer appear in the API reference.

### PR DESCRIPTION
**Pull request by francisek**
Fix #3

### CODE REVIEW

**Review by kelunik — CHANGES_REQUESTED** [review]
For functions it's fine, but we have to be careful with classes, otherwise we exclude all magic methods. Now that I think more about it, maybe we should just apply this logic to functions starting with one or more underscores and for methods only if they start with exactly one underscore?

**Comment by francisek** [comment]
My advice is that the rule should be the same for both functions and methods for easier code writing convention.
So it should be either for names beginning by exactly one underscore or for those beginning by two underscores in which case we should exclude explicitly magic methods.
What do you think about it ?

**Comment by kelunik** [comment]
I don't know if there's any standard way in PHP for that. I think `__` (double) is reserved for methods, so maybe it makes sense to restrict it to `_`. I just created this issue, because I know we use these: https://github.com/amphp/amp/blob/v1.x/lib/functions.php#L784-L898

I think we have to gather more data to decide. I [published a tweet](https://twitter.com/kelunik/status/783387837714534400), maybe we get some answers.

**Comment by francisek** [comment]
Here is what the php doc says about methods ((http://php.net/manual/en/language.oop5.magic.php) :  

> PHP reserves all function names starting with __ as magical. It is recommended that you do not use function names with __ in PHP unless you want some documented magic functionality

and global naming conventions (http://php.net/manual/en/userlandnaming.rules.php) :

> PHP reserves all symbols starting with __ as magical. It is recommended that you do not create symbols starting with __ in PHP unless you want to use documented magical functionality.

**Comment by kelunik** [comment]
I think we should just do everything starting with exactly one underscore. Could you adjust the PR?

**Comment by francisek** [comment]
That sounds better, the PR is adjusted.

**Review by kelunik — APPROVED** [review]

**Comment by kelunik** [comment]
Thanks!

**Pull request merged**
